gcp:
  project: jason-hsbc
  region: europe-west2

llm:
  provider: "gemini" # 可选项: "deepseek", "gemini"

database:
  host: "34.39.2.90"
  port: 5432
  dbname: "default_db"
  user: "nvd11"
  password_env_var: "DB_PASSWORD"
